name: ðŸš€ Build on macOS

on:
  push:

jobs:
  build:
    runs-on: macos-13
    timeout-minutes: 270
    steps:
      - name: ðŸ”„ Checkout Code
        uses: actions/checkout@v4

      - name: ðŸš« Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
          all_but_latest: true

      - name: ðŸ“¦ Install Dependencies
        run: |
          brew update
          brew install ffmpeg libmagic

      - name: ðŸ³ Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3

      - name: ðŸ› ï¸ Set up Git
        run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global credential.helper store
          echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials

      - name: ðŸ“‚ Clone Repository
        run: |
          git clone -b stable https://github.com/Nubuki-all/Enc ${{ secrets.GIT_NAME }}
          cd ${{ secrets.GIT_NAME }}
          # find . -maxdepth 1 -type f -exec rm -f {} +
          git clone -b tgenc-1 https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} ${{ secrets.GIT_NAME }}
          rsync -av ${{ secrets.GIT_NAME }}/ .
          rm -rf ${{ secrets.GIT_NAME }}

      - name: ðŸ¤– Run Bot
        run: |
          cd ${{ secrets.GIT_NAME }}
          docker build -t tetris .
          docker run tetris

      - name: ðŸ” Loop Workflow
        run: |
          git clone -b master https://${{ secrets.SUPER_TOKEN }}@github.com/${{ github.repository }} loop
          cd loop || exit 1
          echo $(( RANDOM - (RANDOM % RANDOM) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow: Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.SUPER_TOKEN }}@github.com/${{ github.repository }} HEAD:master
